name: pyfhd
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - astropy
  - configargparse
  - matplotlib
  - numba
  - numpy
  - pytest
  - scipy
  - setuptools
  - sphinx
  - colorama
  - importlib_resources
  - h5py
  - pre-commit
  - black
  - pip
  - pyinstrument
  - pip:
    - sphinx-rtd-theme
    - sphinx-argparse
    - sphinx-reports
    - pytest-cov
    - pytest-html
    - pytest-html-merger
    - myst-parser
    - healpy
    