name: Publish PyFHD

on:
    release:
        types: [published]

jobs:
    publish-pypi:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v6.3
              with:
                enable-cache: true
                python-version: 3.13

            - name: Sync dependencies
              run: uv sync --frozen --no-dev

            - name: Build distributions
              run: |
                uv build -v

            - name: Publish to PyPI
              run: uv publish --trusted-publishing automatic