name: PyFHD pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.17, 3.11.12, 3.12.7]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6.3
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Download the test data from Zenodo
        run: |
          wget -O PyFHD/resources/test_data/pyfhd_test_data.zip https://zenodo.org/records/15687722/files/pyfhd_test_data.zip?download=1
          unzip PyFHD/resources/test_data/pyfhd_test_data.zip -d PyFHD/resources/test_data
    
      - name: Run tests
        run: uv run coverage run --branch --source=PyFHD -m pytest -m github_actions --html=pyfhd_report.html --self-contained-html

      - name: Get coverage HTML report
        run: uv run coverage html --directory=coverage_html_report --title="PyFHD GitHub Actions Coverage Report"

      - name: Change Title of the Unit Test Report
        run: |
          sed -i 's/<h1 id="title">pyfhd_report.html<\/h1>/<h1 id="title">PyFHD GitHub Actions Unit Test Report<\/h1>/' pyfhd_report.html 
          sed -i 's/<title id="head-title">pyfhd_report.html<\/title>/<title id="head-title">PyFHD GitHub Actions Unit Test Report<\/title>/' pyfhd_report.html
    
      - name: Upload Unit Test HTML Report
        if: ${{ matrix.python-version == '3.12' }}
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: pyfhd_report.html

      - name: Upload Coverage HTML Report Directory
        if: ${{ matrix.python-version == '3.12' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: coverage_html_report/

  deploy-reports:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download unit test report
        uses: actions/download-artifact@v3
        with:
          name: unit-test-report
          path: reports

      - name: Download coverage HTML report
        uses: actions/download-artifact@v3
        with:
          name: coverage-html-report
          path: reports/coverage

      - name: Prepare pages content
        run: |
          mkdir -p gh-pages
          cp reports/pyfhd_report.html gh-pages/
          cp -R reports/coverage_html_report gh-pages/coverage_html_report

      - name: Deploy reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
